baseURL = "https://jracon.xyz/"
locale = "en-us"
sectionPagesMenu = "main"
theme = "risotto"
title = "jracon.xyz"

[caches.images]
dir = ":cacheDir/images"

[markup.goldmark.renderer]
unsafe = true

[params.about]
description = "my personal internet vertex"

[[params.socialLinks]]
icon = "fa-brands fa-discord"
title = "Discord"
url = "https://discord.gg/F8TxYESc"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:9o7qkklz@anonaddy.com"

[[params.socialLinks]]
icon = "fa-brands fa-instagram"
title = "Instagram"
url = "https://www.instagram.com/jracon.xyz"

[params.theme]
palette = "me"
